from __future__ import annotations
import statistics
from collections.abc import Iterable, Mapping, Sequence
from pydantic import BaseModel, ConfigDict, Field

def seed_recall(seed: Iterable[str], context: Iterable[str]) -> float:
    seed_set = set(seed)
    if not seed_set:
        raise ValueError('seed recall is undefined for an empty seed')
    return len(seed_set & set(context)) / len(seed_set)

class BuilderCell(BaseModel):
    model_config = ConfigDict(frozen=True)
    builder: str
    budget: int = Field(gt=0)
    instances: int = Field(ge=0)
    assessable: int = Field(ge=0)
    median_depth: float | None = None
    depths: tuple[int, ...] = ()
    median_realised_tokens: int = 0
    over_budget: int = 0
    seed_recall: dict[str, float] = {}
    median_seed_recall: float | None = None
    mean_seed_recall: float | None = None
    omit_empty: int = 0
    verdicts: dict[str, int] = {}

    @property
    def unassessable_rate(self) -> float | None:
        return None if not self.instances else (self.instances - self.assessable) / self.instances

def cell(builder: str, budget: int, depths: Sequence[int], realised: Sequence[int], instances: int, over_budget: int=0, *, recall: Mapping[str, float] | None=None, omit_empty: int=0, verdicts: Mapping[str, int] | None=None) -> BuilderCell:
    recalls = list((recall or {}).values())
    return BuilderCell(builder=builder, budget=budget, instances=instances, assessable=len(depths) + omit_empty, median_depth=statistics.median(depths) if depths else None, depths=tuple(depths), median_realised_tokens=int(statistics.median(realised)) if realised else 0, over_budget=over_budget, seed_recall=dict(recall or {}), median_seed_recall=statistics.median(recalls) if recalls else None, mean_seed_recall=statistics.fmean(recalls) if recalls else None, omit_empty=omit_empty, verdicts=dict(verdicts or {}))

def table(cells: Sequence[BuilderCell], budgets: Sequence[int]) -> str:
    by: dict[tuple[str, int], BuilderCell] = {(c.builder, c.budget): c for c in cells}
    builders = sorted({c.builder for c in cells})
    nb = len(budgets)
    heads = ' & '.join((f'{b // 1000}K' for b in budgets))
    lines = ['% Generated by `lacuna experiment adequacy-budget`. NOT RQ4: no agent is run.', '\\begin{tabular}{@{}l' + 'r' * (3 * nb) + '@{}}', '\\toprule', '\\textbf{Builder} & \\multicolumn{' + str(nb) + '}{c}{\\textbf{median depth}} &', '\\multicolumn{' + str(nb) + '}{c}{\\textbf{unassessable (\\%)}} &', '\\multicolumn{' + str(nb) + '}{c}{\\textbf{median seed recall (\\%)}} \\\\', '\\cmidrule(lr){2-' + str(1 + nb) + '}\\cmidrule(lr){' + str(2 + nb) + '-' + str(1 + 2 * nb) + '}\\cmidrule(l){' + str(2 + 2 * nb) + '-' + str(1 + 3 * nb) + '}', ' & ' + heads + ' & ' + heads + ' & ' + heads + ' \\\\', '\\midrule']
    for b in builders:
        depths, unass, recall = ([], [], [])
        for bud in budgets:
            c = by.get((b, bud))
            depths.append('---' if c is None or c.median_depth is None else f'{c.median_depth:.0f}')
            r = None if c is None else c.unassessable_rate
            unass.append('---' if r is None else f'{100 * r:.0f}')
            m = None if c is None else c.median_seed_recall
            recall.append('---' if m is None else f'{100 * m:.1f}')
        lines.append(f'{b:34} & ' + ' & '.join(depths + unass + recall) + ' \\\\')
    lines += ['\\bottomrule', '\\end{tabular}']
    varying = {c.builder for c in cells if any((o.builder == c.builder and o.assessable != c.assessable for o in cells))}
    if varying:
        lines.append('% medians are over the assessable subset, which grows with the budget, so they are NOT comparable across columns; the assessable count is.')
    infinite = sum((c.omit_empty for c in cells))
    if infinite:
        lines.append(f'% {infinite} assessable contexts have Omit empty (depth infinity, Def. 3.7) and are counted as assessable but excluded from the depth medians.')
    over = sum((c.over_budget for c in cells))
    if over:
        lines.append(f'% WARNING: {over} builder results exceeded their budget; the comparison is not at equal budget and must not be reported (D54).')
    return '\n'.join(lines)
